LANGUAGES = [
    "af",
    "sq",
    "am",
    "ar",
    "hy",
    "az",
    "eu",
    "be",
    "bn",
    "bs",
    "bg",
    "ca",
    "ceb",
    "ny",
    "zh-cn",
    "zh-tw",
    "co",
    "hr",
    "cs",
    "da",
    "nl",
    "en",
    "eo",
    "et",
    "tl",
    "fi",
    "fr",
    "fy",
    "gl",
    "ka",
    "de",
    "el",
    "gu",
    "ht",
    "ha",
    "haw",
    "iw",
    "he",
    "hi",
    "hmn",
    "hu",
    "is",
    "ig",
    "id",
    "ga",
    "it",
    "ja",
    "jw",
    "kn",
    "kk",
    "km",
    "ko",
    "ku",
    "ky",
    "lo",
    "la",
    "lv",
    "lt",
    "lb",
    "mk",
    "mg",
    "ms",
    "ml",
    "mt",
    "mi",
    "mr",
    "mn",
    "my",
    "ne",
    "no",
    "or",
    "ps",
    "fa",
    "pl",
    "pt",
    "pa",
    "ro",
    "ru",
    "sm",
    "gd",
    "sr",
    "st",
    "sn",
    "sd",
    "si",
    "sk",
    "sl",
    "so",
    "es",
    "su",
    "sw",
    "sv",
    "tg",
    "ta",
    "te",
    "th",
    "tr",
    "uk",
    "ur",
    "ug",
    "uz",
    "vi",
    "cy",
    "xh",
    "yi",
    "yo",
    "zu"
]
SERVICE_URLS = ('translate.google.ac', 'translate.google.ad', 'translate.google.ae',
                'translate.google.al', 'translate.google.am', 'translate.google.as',
                'translate.google.at', 'translate.google.az', 'translate.google.ba',
                'translate.google.be', 'translate.google.bf', 'translate.google.bg',
                'translate.google.bi', 'translate.google.bj', 'translate.google.bs',
                'translate.google.bt', 'translate.google.by', 'translate.google.ca',
                'translate.google.cat', 'translate.google.cc', 'translate.google.cd',
                'translate.google.cf', 'translate.google.cg', 'translate.google.ch',
                'translate.google.ci', 'translate.google.cl', 'translate.google.cm',
                'translate.google.cn', 'translate.google.co.ao', 'translate.google.co.bw',
                'translate.google.co.ck', 'translate.google.co.cr', 'translate.google.co.id',
                'translate.google.co.il', 'translate.google.co.in', 'translate.google.co.jp',
                'translate.google.co.ke', 'translate.google.co.kr', 'translate.google.co.ls',
                'translate.google.co.ma', 'translate.google.co.mz', 'translate.google.co.nz',
                'translate.google.co.th', 'translate.google.co.tz', 'translate.google.co.ug',
                'translate.google.co.uk', 'translate.google.co.uz', 'translate.google.co.ve',
                'translate.google.co.vi', 'translate.google.co.za', 'translate.google.co.zm',
                'translate.google.co.zw', 'translate.google.com.af', 'translate.google.com.ag',
                'translate.google.com.ai', 'translate.google.com.ar', 'translate.google.com.au',
                'translate.google.com.bd', 'translate.google.com.bh', 'translate.google.com.bn',
                'translate.google.com.bo', 'translate.google.com.br', 'translate.google.com.bz',
                'translate.google.com.co', 'translate.google.com.cu', 'translate.google.com.cy',
                'translate.google.com.do', 'translate.google.com.ec', 'translate.google.com.eg',
                'translate.google.com.et', 'translate.google.com.fj', 'translate.google.com.gh',
                'translate.google.com.gi', 'translate.google.com.gt', 'translate.google.com.hk',
                'translate.google.com.jm', 'translate.google.com.kh', 'translate.google.com.kw',
                'translate.google.com.lb', 'translate.google.com.ly', 'translate.google.com.mm',
                'translate.google.com.mt', 'translate.google.com.mx', 'translate.google.com.my',
                'translate.google.com.na', 'translate.google.com.ng', 'translate.google.com.ni',
                'translate.google.com.np', 'translate.google.com.om', 'translate.google.com.pa',
                'translate.google.com.pe', 'translate.google.com.pg', 'translate.google.com.ph',
                'translate.google.com.pk', 'translate.google.com.pr', 'translate.google.com.py',
                'translate.google.com.qa', 'translate.google.com.sa', 'translate.google.com.sb',
                'translate.google.com.sg', 'translate.google.com.sl', 'translate.google.com.sv',
                'translate.google.com.tj', 'translate.google.com.tr', 'translate.google.com.tw',
                'translate.google.com.ua', 'translate.google.com.uy', 'translate.google.com.vc',
                'translate.google.com.vn', 'translate.google.com', 'translate.google.cv',
                'translate.google.cz', 'translate.google.de', 'translate.google.dj',
                'translate.google.dk', 'translate.google.dm', 'translate.google.dz',
                'translate.google.ee', 'translate.google.es', 'translate.google.eu',
                'translate.google.fi', 'translate.google.fm', 'translate.google.fr',
                'translate.google.ga', 'translate.google.ge', 'translate.google.gf',
                'translate.google.gg', 'translate.google.gl', 'translate.google.gm',
                'translate.google.gp', 'translate.google.gr', 'translate.google.gy',
                'translate.google.hn', 'translate.google.hr', 'translate.google.ht',
                'translate.google.hu', 'translate.google.ie', 'translate.google.im',
                'translate.google.io', 'translate.google.iq', 'translate.google.is',
                'translate.google.it', 'translate.google.je', 'translate.google.jo',
                'translate.google.kg', 'translate.google.ki', 'translate.google.kz',
                'translate.google.la', 'translate.google.li', 'translate.google.lk',
                'translate.google.lt', 'translate.google.lu', 'translate.google.lv',
                'translate.google.md', 'translate.google.me', 'translate.google.mg',
                'translate.google.mk', 'translate.google.ml', 'translate.google.mn',
                'translate.google.ms', 'translate.google.mu', 'translate.google.mv',
                'translate.google.mw', 'translate.google.ne', 'translate.google.nf',
                'translate.google.nl', 'translate.google.no', 'translate.google.nr',
                'translate.google.nu', 'translate.google.pl', 'translate.google.pn',
                'translate.google.ps', 'translate.google.pt', 'translate.google.ro',
                'translate.google.rs', 'translate.google.ru', 'translate.google.rw',
                'translate.google.sc', 'translate.google.se', 'translate.google.sh',
                'translate.google.si', 'translate.google.sk', 'translate.google.sm',
                'translate.google.sn', 'translate.google.so', 'translate.google.sr',
                'translate.google.st', 'translate.google.td', 'translate.google.tg',
                'translate.google.tk', 'translate.google.tl', 'translate.google.tm',
                'translate.google.tn', 'translate.google.to', 'translate.google.tt',
                'translate.google.us', 'translate.google.vg', 'translate.google.vu',
                'translate.google.ws')
LANGUAGE_TRANSLATE = {
    "af": "南非语",
    "sq": "阿尔巴尼亚语",
    "am": "阿姆哈拉语",
    "ar": "阿拉伯语",
    "hy": "亚美尼亚语",
    "az": "阿塞拜疆",
    "eu": "巴斯克",
    "be": "白俄罗斯语",
    "bn": "孟加拉",
    "bs": "波斯尼亚语",
    "bg": "保加利亚语",
    "ca": "加泰罗尼亚语",
    "ceb": "宿务语",
    "ny": "尼昂加语",
    "zh-cn": "简体中文",
    "zh-tw": "繁体中文",
    "co": "科西嘉",
    "hr": "克罗地亚语",
    "cs": "捷克语",
    "da": "丹麦语",
    "nl": "荷兰语",
    "en": "英语",
    "eo": "世界语",
    "et": "爱沙尼亚语",
    "tl": "菲律宾语",
    "fi": "芬兰语",
    "fr": "法语",
    "fy": "弗里斯兰语",
    "gl": "加利西亚语",
    "ka": "乔治亚风格",
    "de": "德语",
    "el": "希腊语",
    "gu": "古吉拉特语",
    "ht": "海地克里奥尔语",
    "ha": "豪萨语",
    "haw": "夏威夷语",
    "he": "希伯来语",
    "hi": "印地语",
    "hmn": "苗语",
    "hu": "匈牙利",
    "is": "冰岛语",
    "ig": "伊博语",
    "id": "印度尼西亚语",
    "ga": "爱尔兰语",
    "it": "意大利语",
    "ja": "日本语",
    "jw": "爪哇语",
    "kn": "卡纳达语",
    "kk": "哈萨克语",
    "km": "高棉语",
    "ko": "韩国语",
    "ku": "库尔德语",
    "ky": "吉尔吉斯斯坦",
    "lo": "老挝语",
    "la": "拉丁语",
    "lv": "拉脱维亚语",
    "lt": "立陶宛语",
    "lb": "卢森堡",
    "mk": "马其顿语",
    "mg": "马尔加什语",
    "ms": "马来语",
    "ml": "马拉雅拉姆语",
    "mt": "马耳他的",
    "mi": "毛利语",
    "mr": "马拉地语",
    "mn": "蒙古语",
    "my": "缅甸语",
    "ne": "尼泊尔语",
    "no": "挪威",
    "or": "奥迪亚语",
    "ps": "普什图语",
    "fa": "波斯语",
    "pl": "抛光",
    "pt": "葡萄牙语",
    "pa": "旁遮普语",
    "ro": "罗马尼亚语",
    "ru": "俄语",
    "sm": "萨摩亚语",
    "gd": "苏格兰盖尔语",
    "sr": "塞尔维亚",
    "st": "塞索托",
    "sn": "绍娜",
    "sd": "辛迪",
    "si": "辛哈拉",
    "sk": "斯洛伐克文",
    "sl": "斯洛文尼亚文",
    "so": "索马里",
    "es": "西班牙语",
    "su": "巽他语",
    "sw": "斯瓦希里语",
    "sv": "瑞典语",
    "tg": "塔吉克语",
    "ta": "泰米尔语",
    "te": "泰卢固语",
    "th": "泰语",
    "tr": "土耳其语",
    "uk": "乌克兰语",
    "ur": "乌尔都语",
    "ug": "维吾尔语",
    "uz": "乌兹别克语",
    "vi": "越南语",
    "cy": "威尔士语",
    "xh": "科萨语",
    "yi": "依地语",
    "yo": "约鲁巴",
    "zu": "祖鲁语"
}


class SelectItemError(BaseException):
    def __init__(self, *args):
        super(SelectItemError, self).__init__(args[0])
